name: Build Angular Workspace

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node Modules
      run: |
        npm install
        
    - name: Build Sample Application 1
      run: |
        npm run start:sample1
    
    - name: Build Sample Application 2
      run: |
        npm run start:sample2
